// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Persistence;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20260216141544_RemoveCreatedAtFromExercise")]
    partial class RemoveCreatedAtFromExercise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("backend.Domain.Entities.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid");

                    b.HasKey("ExerciseId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("ExerciseMuscles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Muscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bae51a45-0eb0-4e51-97ae-e70bbe009eb6"),
                            Name = "Pectoraux"
                        },
                        new
                        {
                            Id = new Guid("c8498283-5483-491f-adbc-9dad4d591196"),
                            Name = "Dos"
                        },
                        new
                        {
                            Id = new Guid("66cefe28-52e3-46bc-8fc6-2c52090b1922"),
                            Name = "Épaules"
                        },
                        new
                        {
                            Id = new Guid("9a1fda82-7bcb-432f-85b6-d79c9bee783d"),
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("992bf433-2f92-4569-ac29-85b8f7066ff9"),
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("fcb9abb3-2715-4d5a-b0db-30c82dc1f60a"),
                            Name = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("cf5d0331-4cca-4b0e-887d-8f453cf497a3"),
                            Name = "Ischios"
                        },
                        new
                        {
                            Id = new Guid("9bb5a066-0706-4dd1-8faa-a07700e5a50f"),
                            Name = "Fessiers"
                        },
                        new
                        {
                            Id = new Guid("62cc5531-ebdb-4b8e-8227-505c300285cc"),
                            Name = "Mollets"
                        },
                        new
                        {
                            Id = new Guid("6b93f3f6-73bb-4147-83c3-401c5a698b2a"),
                            Name = "Abdos"
                        },
                        new
                        {
                            Id = new Guid("7490b915-3115-4898-b86a-1855c095e814"),
                            Name = "Lombaires"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("backend.Domain.Entities.User", "User")
                        .WithMany("Exercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Entities.ExerciseMuscle", b =>
                {
                    b.HasOne("backend.Domain.Entities.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("backend.Domain.Entities.User", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
